#!/bin/bash 

export S_FP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MMMV_DEVEL_TOOLS_HOME="`cd $S_FP_DIR/../../../../../../; pwd`"
unset S_FP_DIR

export UPGUID_HOME="$MMMV_DEVEL_TOOLS_HOME/src/mmmv_devel_tools/GUID_trace/src/UpGUID"
ruby -Ku $UPGUID_HOME/src/bonnet/upguid.rb $1 $2 $3 $4 $5 $6 $7 $8 $9 

