#!/usr/bin/env bash

export S_FP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MMMV_DEVEL_TOOLS_HOME="`cd $S_FP_DIR/../../../../; pwd`"
unset S_FP_DIR

export MMMV_CRYPT_T1_HOME="$MMMV_DEVEL_TOOLS_HOME/src/mmmv_devel_tools/mmmv_crypt_t1" 
nice -n 2 ruby $MMMV_CRYPT_T1_HOME/src/bonnet/mmmv_decrypt_t1.rb $1 $2 $3 $4 $5 $6 $7 $8 $9 

