#!/home/zornilemma/m_local/bin_p/Ruby/1.8.7/bin/ruby
#==========================================================================
puts "hei\nrida2"

# The bug has probably something to do with
# the order of extraction. If the REEN in the
# next puts line is corrected to REN, the 
# Renessaator gets confused. 
puts "#REENESSAATOR_BLOCK_START"

# RENESSAATOR_BLOCK_START
# RENESSAATOR_BLOCK_ID=block_7daa1c0e-261b-41ff-8ecc-85bca4651f93_city
# RENESSAATOR_SOURCE_LANGUAGE=php
# RENESSAATOR_SOURCE_START
# echo("Teerei223");
# RENESSAATOR_SOURCE_END  
#RENESSAATOR_AUTOGENERATED_TEXT_START
Teerei223
# RENESSAATOR_AUTOGENERATED_TEXT_END 
# RENESSAATOR_BLOCK_END


