#!/usr/bin/env bash
#==========================================================================
#
# Copyright 2014, martin.vahi@softf1.com that has an
# Estonian personal identification code of 38108050020.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the following
# conditions are met:
#
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer
#   in the documentation and/or other materials provided with the
#   distribution.
# * Neither the name of the Martin Vahi nor the names of its
#   contributors may be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#==========================================================================


# It's a T-pipe for the sound that is sent to the speakers.
func_mmmv_speakers2wav_t1() { # S_FP_OUTPUT_FILE_WITH_FILE_EXTENSION
    local S_FP_OUTPUT_FILE_WITH_FILE_EXTENSION="$1"
    if [ "$S_FP_OUTPUT_FILE_WITH_FILE_EXTENSION" == "" ]; then
            echo ""
            echo "This script takes exactly one argument, which "
            echo "is the name of the output WAV or OGG or MP3 file."
            echo ""
            exit;
    fi
    #----------------
    local S_TIMESTAMP="`date +%Y`_`date +%m`_`date +%d`_`date +%H`:`date +%M`:`date +%S`"
    #S_FP_prefix="`echo $S_TIMESTAMP`_"
    local S_TMP_0="_speakers2wav_tmp.raw"
    local S_FP_RAW="/tmp/$S_TIMESTAMP$S_TMP_0"
    #----------------
    echo ""
    echo "The recording can be stopped by pressing Ctrl-C."
    echo "After the recording has been stopped, encoding starts."
    echo "The encoding can take a while."
    echo ""
    echo "Recording ..."
    #----------------
    # Credits for the audio commands go partly to the tutorial at
    # http://jan.newmarch.name/LinuxSound/Sampled/PulseAudio/
    #----------------
    pacat --record --format=s32le --rate=44100 -d 0  --volume=30000 $S_FP_RAW  # records it
    echo "" # to get the Ctrl-C console output to a separate line
    #aplay --format=S32_LE --rate=44100 --channels=2 $S_FP_RAW                 # plays it
    echo "Encoding ..."
    ffmpeg -f s32le -ar 44100 -ac 2 -i $S_FP_RAW  $S_FP_OUTPUT_FILE_WITH_FILE_EXTENSION   # converts it
    echo ""
    echo "Encoding complete. Deleting raw copy..."
    rm -f $S_FP_RAW
    echo "Raw copy deleted."
    echo ""
} # func_mmmv_speakers2wav_t1

func_mmmv_speakers2wav_t1 $1

