#!/usr/bin/ruby
#--------------------------------------------------------------------------

puts "Howdy from Hello World, line X."
# RENESSAATOR_BLOCK_START
# RENESSAATOR_SOURCE_LANGUAGE=Ruby
# RENESSAATOR_BLOCK_ID=template1_block1
#
# RENESSAATOR_SOURCE_START
# x=44
# puts "puts\"But this line has been autogenerated,"+x.to_s+" \""
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START

 The autogenerated text part of a Renessaator block 
 is overwritten every time the Renessaator block gets executed.

# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END

#--------------------------------------------------------------------------

