#!/usr/bin/env rake

require 'rake'
require 'pathname'

if !defined? THIS_PROEJCT_HOME
   ob_pth=Pathname.new(__FILE__).realpath.parent
   THIS_PROEJCT_HOME=ob_pth.to_s
   ENV["THIS_PROEJCT_HOME"]=THIS_PROEJCT_HOME
end # if

if !defined? MMMV_DEVEL_TOOLS_HOME
   ob_pth=Pathname.new(__FILE__).realpath.parent
   ob_pth_1=ob_pth.parent.parent.parent.parent.parent
   MMMV_DEVEL_TOOLS_HOME=ob_pth_1.to_s
end # if

require(MMMV_DEVEL_TOOLS_HOME+
"/src/bonnet/mmmv_devel_tools_initialization_t1.rb")

task :run_renessaator do
   puts "\nRunning the renessaator task from the Rakefile ..."

   s_fp_x=THIS_PROEJCT_HOME+"/the_soruce_X.js"
   s_fp_y=THIS_PROEJCT_HOME+"/the_soruce_Y.js"
   ar_fp_files_to_edit_with_the_renessaator=[s_fp_x,s_fp_y]

   s_fp_a_recursively_watched_folder=THIS_PROEJCT_HOME+
   "/code_generation_scripts"
   s_this_rakefile=THIS_PROEJCT_HOME+"/Rakefile"
   ar=[s_fp_a_recursively_watched_folder,s_this_rakefile]
   ar_files_to_watch_for_changes_in_addition_to_the_renessaator_edited_files=ar

   i_watch_cache_max_size=100 # in number of files

   C_mmmv_devel_tools_global_singleton.run_renessaator_t1(
   ar_fp_files_to_edit_with_the_renessaator,
   ar_files_to_watch_for_changes_in_addition_to_the_renessaator_edited_files,
   i_watch_cache_max_size)

   puts "Rakefile task complete.\n\n"
end # run_renessaator

task :default do
   ar_task_names=Array.new
   Rake.application.tasks.each {|x_task| ar_task_names<<x_task.to_s}
   ar_task_names.sort!
   puts "\n\nAvailable Rake functions:\n\n"
   s_1="                "
   ar_task_names.each do |s_task_name|
      puts s_1+s_task_name.to_s
   end # loop
   puts "\n\n"
end # default

#==========================================================================

