#!/bin/bash 


if [ "$MMMV_DEVEL_TOOLS_HOME" == "" ]; then
        echo"" 
        echo"" 
        echo "Mandatory environment variable, MMMV_DEVEL_TOOLS_HOME, has not been set. "
        echo"" 
        echo"" 
        exit;
fi

JUMPGUID_HOME="$MMMV_DEVEL_TOOLS_HOME/src/mmmv_devel_tools/GUID_trace/src/JumpGUID"
ruby -Ku $JUMPGUID_HOME/src/devel/core/bonnet/jumpguid_core.rb $1 $2 $3 $4 $5 $6 $7 $8 $9 

