#!/usr/bin/ruby
#==========================================================================
=begin
    The sole purpose of this file is to contain test data for
    the Renessaator selftests.
=end
#==========================================================================
puts "Howdy from template1."
# RENESSAATOR_BLOCK_START
# RENESSAATOR_SOURCE_LANGUAGE=Ruby
# RENESSAATOR_BLOCK_ID=template1_block1
#
# RENESSAATOR_SOURCE_START
# x=44
# puts "puts 'This is autogenerated "+x.to_s+" text'"
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START

# The generated text can contain comments.

# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END



#==========================================================================
