#!/usr/bin/ruby
#==========================================================================
=begin
    The sole purpose of this file is to contain test data for
    the Renessaator selftests.
=end
#==========================================================================
puts "Howdy from template4."
# RENESSAATOR_BLOCK_START
# RENESSAATOR_BLOCK_ID=template4_block1
# RENESSAATOR_SOURCE_LANGUAGE=Ruby 
#
# RENESSAATOR_SOURCE_START
# puts "# The template 4 tests for the handling of multiple blocks"
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START
# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END

puts "\n--------separator1---------\n"

# RENESSAATOR_BLOCK_START
# RENESSAATOR_SOURCE_LANGUAGE=Ruby 
#
# RENESSAATOR_SOURCE_START
# puts "# This block misses the optional block ID parameter."
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START
# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END

puts "\n--------separator2---------\n"

# RENESSAATOR_BLOCK_START
# RENESSAATOR_BLOCK_ID=template4_block3
# RENESSAATOR_SOURCE_LANGUAGE=Ruby 
#
# RENESSAATOR_SOURCE_START
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START
# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END

puts "\n--------separator3---------\n"


#==========================================================================
