#!/usr/bin/ruby
#==========================================================================
=begin
    The sole purpose of this file is to contain test data for
    the Renessaator selftests.
=end
#==========================================================================
puts "Howdy from template3."
# RENESSAATOR_BLOCK_START
# RENESSAATOR_BLOCK_ID=template3_block1
#
# RENESSAATOR_SOURCE_START
# x=44
# puts "# Template 3 misses the RENESSAATOR_SOURCE_LANGUAGE and "
# puts "# is expected to cause the Renessaator to throw error "+
#   "with message code 6."
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START
# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END



#==========================================================================
