#!/usr/bin/ruby
#==========================================================================
=begin
    The sole purpose of this file is to contain test data for
    the Renessaator selftests.
=end
#==========================================================================
puts "Howdy from template5."
# RENESSAATOR_BLOCK_START
# RENESSAATOR_BLOCK_ID=template5_block1
# RENESSAATOR_SOURCE_LANGUAGE=Ruby 
#
# RENESSAATOR_SOURCE_START
# puts "# not determined yet."
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START
# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END


#==========================================================================
