#!/usr/bin/ruby
#==========================================================================
=begin
    The sole purpose of this file is to contain test data for
    the Renessaator selftests.
=end
#==========================================================================
puts "Howdy from template1."
# RENESSAATOR_BLOCK_START
# RENESSAATOR_SOURCE_LANGUAGE=Ruby
# RENESSAATOR_BLOCK_ID=template1_block1
#
# RENESSAATOR_SOURCE_START
# puts ENV['RENESSAATOR_PROCESS_ID'].to_s
# RENESSAATOR_SOURCE_END
#
# RENESSAATOR_AUTOGENERATED_TEXT_START


# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END

# RENESSAATOR_BLOCK_START
# RENESSAATOR_BLOCK_ID=block_7daa1c0e-122b-4317-c04c-e510e142dbb8_city
# RENESSAATOR_SOURCE_LANGUAGE=Ruby
# RENESSAATOR_SOURCE_START
# puts "hei"
# RENESSAATOR_SOURCE_END
# 
# RENESSAATOR_AUTOGENERATED_TEXT_START
hei

# RENESSAATOR_AUTOGENERATED_TEXT_END
# RENESSAATOR_BLOCK_END



#==========================================================================
